version: '3.8'

services:
  # MySQL Database Service
  mysql:
    image: mysql:8.0
    container_name: wp-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress_db
      MYSQL_USER: wp_user
      MYSQL_PASSWORD: 123
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - wp-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  # WordPress Application Service
  wordpress:
    image: wordpress:php8.1-fpm
    container_name: wp-app
    restart: unless-stopped
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_NAME: wordpress_db
      WORDPRESS_DB_USER: wp_user
      WORDPRESS_DB_PASSWORD: 123
      WORDPRESS_DEBUG: 'false'
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - wp-network
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M

  # Nginx Web Server Service
  nginx:
    image: nginx:alpine
    container_name: wp-nginx
    restart: unless-stopped
    ports:
      - "${NGINX_PORT}:80"
    depends_on:
      - wordpress
    volumes:
      - wordpress_data:/var/www/html:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - nginx_logs:/var/log/nginx
    networks:
      - wp-network
    deploy:
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M

# Named Volumes for Data Persistence
volumes:
  mysql_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./volumes/mysql
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./volumes/wordpress
  nginx_logs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./volumes/nginx-logs

# Custom Bridge Network
networks:
  wp-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1
