version: '3.8'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_password
      MYSQL_DATABASE: wordpress_db
      MYSQL_USER: wp_user
      MYSQL_PASSWORD_FILE: /run/secrets/mysql_password
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - wp-network
    secrets:
      - mysql_root_password
      - mysql_password
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager

  wordpress:
    image: wordpress:php8.1-fpm
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_NAME: wordpress_db
      WORDPRESS_DB_USER: wp_user
      WORDPRESS_DB_PASSWORD_FILE: /run/secrets/mysql_password
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - wp-network
    secrets:
      - mysql_password
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - wordpress_data:/var/www/html:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - nginx_logs:/var/log/nginx # Mount untuk nginx_logs
    networks:
      - wp-network
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager

volumes:
  mysql_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/vboxuser/wordpress-docker/volumes/mysql

  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/vboxuser/wordpress-docker/volumes/wordpress

  nginx_logs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/vboxuser/wordpress-docker/volumes/nginx-logs

networks:
  wp-network:
    driver: overlay
    attachable: true

secrets:
  mysql_root_password:
    external: true
  mysql_password:
    external: true
